version: '2.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8876:80
    #        networks:
    #            - elastic
    depends_on:
      - app
    container_name: opbeans_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    #        networks:
    #            - elastic
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: opbeans_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lardocker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8102:3306
    #        networks:
    #            - elastic
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: opbeans_db

#networks:
#    default:
#        external:
#            name: elastic

